service:
  id: ai-spring-thymeleaf

project:
  home: /apps/ai/${spring.profiles.active}/full-stack-developer/ai-spring-thymeleaf/


spring:
    greeting: String MVC, Thymeleaf, Bootstrap, JQuery
    thymeleaf:
#      mode: HTML
      prefix: classpath:/templates/thymeleaf/
      suffix: .html
      cache: false
    profiles:
      active: local

logging:
  file: ${project.home}/logs/${service.id}.log
  level:
    root: INFO
    org.ai: DEBUG
server:
  error:
    path: /error

---
spring:
  profiles: local
  datasource:
    platform: h2
    driverClassName: org.h2.Driver
    # this is default url that spring-boot will load , if you change, those schemal.sql and data.sql in classpath will not work
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false
    username: sa
    password:
---
spring:
  profiles: dev
  greeting: String MVC, Thymeleaf, Bootstrap, Jquery
  thymeleaf:
    cache: true
  datasource:
    url: jdbc:mysql://localhost:3306/spring_thymeleaf
    username: root
    password: root
    # Spring Boot can deduce from most of database url
    driver-class-name: com.mysql.jdbc.Driver
---
spring:
  profiles: sit
  greeting: String MVC, Thymeleaf, Bootstrap, Jquery
  thymeleaf:
    cache: true
---
spring:
  profiles: prod
  greeting: String MVC, Thymeleaf, Bootstrap, Jquery
  thymeleaf:
    cache: true
